steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform init \
    -backend-config="bucket=$PROJECT_ID-tf-state" \
    -backend-config="prefix=terraform_gcp/dataflow"
  dir: terraform
      
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - plan
  dir: terraform

- id: 'tf destroy'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - destroy
  - -auto-approve
  dir: terraform

options:
  env:
    - TF_VAR_project_id=$PROJECT_ID
    - PROJECT_NUMBER=$PROJECT_NUMBER
tags:
  - terraform
  - dataflow

timeout: 1200s
