steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform init \
    -backend-config="bucket=$PROJECT_ID-tf-state" \
    -backend-config="prefix=terraform_gcp/gke"
      
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - plan

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - apply
  - -auto-approve

# - id: 'tf destroy'
#   name: 'hashicorp/terraform:1.0.0'
#   args: 
#   - destroy
#   - -auto-approve

options:
  env:
    - TF_VAR_project_id=$PROJECT_ID

tags:
  - terraform
  - gke

timeout: 1200s
