# Ref https://github.com/bitnami/charts/tree/master/bitnami/external-dns
provider: google
sources:
- ingress
google:
  project: <YOUR-PROJECT-ID>
serviceAccount:
  create: true
  name: external-dns
  annotations:
    iam.gke.io/gcp-service-account: external-dns@<YOUR-PROJECT-ID>.iam.gserviceaccount.com
