# Ref https://github.com/kubernetes/ingress-nginx/tree/master/charts/ingress-nginx
controller:
  replicaCount: 2
  service:
    # nginx ingress load balance. Reserve a static external IP for it.
    loadBalancerIP: ""
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - ingress-nginx
            - key: app.kubernetes.io/component
              operator: In
              values:
              - controller
          topologyKey: kubernetes.io/hostname
defaultBackend:
  enabled: true
admissionWebhooks:
  enabled: false
