# Ref https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - alertmanager.<UPDATE-WITH-YOUR-DOMAIN>
grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - grafana.<UPDATE-WITH-YOUR-DOMAIN>
prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - prometheus.<UPDATE-WITH-YOUR-DOMAIN>
