steps:
# Terraform
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform init \
    -backend-config="bucket=$PROJECT_ID-tf-state" \
    -backend-config="prefix=terraform_gcp/gke-standard"
  dir: terraform
      
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - plan
  dir: terraform

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - apply
  - -auto-approve
  dir: terraform

# Kubernetes
- id: git-clone
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/GoogleCloudPlatform/cloud-builders-community']

- id: build-helm
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/helm', 'helm']
  dir: cloud-builders-community
  
- id: test-helm
  name: 'gcr.io/$PROJECT_ID/helm:latest'
  args: ['version', '--client']
  env:
    - SKIP_CLUSTER_CONFIG=true

- id: create-namespaces
  name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'namespaces.yaml']
  dir: k8s

- id: deploy-ingress-nginx
  name: 'gcr.io/$PROJECT_ID/helm:latest'
  args: ['upgrade', '--install', 'ingress-nginx', 
   'ingress-nginx/ingress-nginx',
   '--version', '4.0.10', 
   '--namespace', 'nginx',
   '-f', 'ingress-nginx.yaml',
  ]
  env:
  - 'HELM_REPO_NAME=ingress-nginx'
  - 'HELM_REPO_URL=https://kubernetes.github.io/ingress-nginx'
  dir: k8s

- id: deploy-kube-prometheus
  name: 'gcr.io/$PROJECT_ID/helm:latest'
  args: ['upgrade', '--install', 'prometheus-stack',
   'prometheus-community/kube-prometheus-stack',
   '--version', '36.0.1', 
   '--namespace', 'monitoring',
   '-f', 'prometheus-stack.yaml',
  ]
  env:
  - 'HELM_REPO_NAME=prometheus-community'
  - 'HELM_REPO_URL=https://prometheus-community.github.io/helm-charts'
  dir: k8s

- id: deploy-jenkins
  name: 'gcr.io/$PROJECT_ID/helm:latest'
  args: ['upgrade', '--install', 'jenkins',
  'jenkinsci/jenkins', 
  '--version', '4.1.8', 
  '--namespace', 'jenkins',
   '-f', 'jenkins.yaml'
  ]
  env:
  - 'HELM_REPO_NAME=jenkinsci'
  - 'HELM_REPO_URL=https://charts.jenkins.io'
  dir: k8s

options:
  env:
    - TF_VAR_project_id=$PROJECT_ID
    - 'CLOUDSDK_COMPUTE_REGION=southamerica-east1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gke-std-sandbox'

tags:
  - terraform
  - helm
  - gke-standard

timeout: 1200s
