steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    terraform init \
    -backend-config="bucket=$PROJECT_ID-tf-state" \
    -backend-config="prefix=terraform_gcp/cloudarmor"

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - destroy
  - -auto-approve

options:
  env:
    - TF_VAR_project_id=$PROJECT_ID
tags:
  - terraform
  - cloud-foundation

timeout: 1200s
