steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - init
  - -backend-config="bucket=$PROJECT_ID-tf-state"
  - -backend-config="prefix=terraform_gcp/cost-management"
  
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - plan

- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  args: 
  - apply
  - -auto-approve
